### ISSUE TITLE
[1.20.1] Client crash interaction with Industrial Forgoing

### ISSUE THREAD

**Issue by daedalus4096** [Kotori316/FluidTank2#18]
Earlier this evening, I encountered a nasty crash in a modpack containing this mod, Industrial Forgoing, and a few others, on 1.20.1 multiplayer.  I placed a Wood Tank filled with Latex into an Industrial Forgoing Latex Processing Unit to fill the device.  The tank was drained and then the empty tank was sucked out of the device through the hopper beneath it into a chest.  When I opened said chest, my client crashed; this behavior was repeatable.  Breaking said chest also resulted in a client crash.  Before/while I was disconnected, my player picked up the tank stack, so when I logged back in and opened my inventory, the client crashed again with the attached crash report.  It was like the item stack was poisoned and any attempt to render it resulted in an immediate crash.  The server stayed up fine during this whole experience, but the server op had to use the /clear command to delete the tank from my inventory before I could continue safely.

[crash-2023-10-08_18.47.08-client.txt](https://github.com/Kotori316/FluidTank2/files/12843423/crash-2023-10-08_18.47.08-client.txt)

**Comment by Kotori316** [comment]
I'm sorry for that inconvenience. I'll take a look for this issue.

**Comment by Kotori316** [comment]
In my environment, I can't reproduce the crash, but I added some code to prevent the exception reported in your crash report.
I released v20.7.4 on [Modrinth](https://modrinth.com/mod/large-fluid-tank/version/9pneQp42), Curse and GitHub Release. Could you try it?

**Comment by daedalus4096** [comment]
I'll let my server admin know that it's available and hopefully he'll include it in the next modpack update.  I don't know when that'll be, so it probably makes sense to close this ticket in the meantime.  I'll do so.  I can open a new one if there's a new issue.  Thanks for the quick fix, and for the nice mod!
