### ISSUE TITLE
Cant see the recipes for the tanks in REI on 1.20.1 Fabric

### ISSUE THREAD

**Issue by Zetherion** [Kotori316/FluidTank2#19]
Exactly what the title says. I click on the tanks and I cant see the recipe of them. I already installed the lib required mentioned on the mods page on modrinth and it doesn't work.

**Comment by Zetherion** [comment]
Found the link on curseforge about the recipes and they dont work either.

**Comment by Kotori316** [comment]
Give me the log file saved at `logs/fluidtank-debug.log`.

**Comment by Kotori316** [comment]
Related to https://legacy.curseforge.com/minecraft/mc-mods/largefluidtank-fabric?comment=13 and Moonlight/issues/165

**Comment by rrwatson** [comment]
Is this able to be resolved? Encountering same issue with MoonlightLib installed and it is a dependency of other mods.
