### ISSUE TITLE
Just a question (Neoforge: 21.1.50  Minecraft: 1.21.1 Fluid Tank: 21.1.0) (No recipes for fluid tanks)

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [Kotori316/FluidTank2#439]
For the fluid tanks if the recipe's are not shown, shouldn't I still be able to create the fluid tanks anyway? As of right now I'm not able to create the fluid tanks unless I get the items from creative mode.

You most likely know of this already, but just thought you'd like to know anyway.

**Comment by Kotori316** [comment]
I'll check. It's not intended. Vanilla material tanks should be able to be crafted in survival.

**Comment by Kotori316** [comment]
I can craft the tank in my environment.

| Wood | Stone |
|--------|--------|
| ![2024-09-12_11 40 28](https://github.com/user-attachments/assets/bebf7e29-0af8-4d50-9769-1c79ed21dee7) | ![2024-09-12_11 40 42](https://github.com/user-attachments/assets/61b01475-8017-433f-8021-a93165f151d6) | 

I think there is a log file named `fluidtank-debug.log` in `log` dir. Could you find and upload the file? It has the information of loaded recipes. I attach the file in my env.
[fluidtank-debug.log](https://github.com/user-attachments/files/16978490/fluidtank-debug.log)

**Comment by DatrixTheHybridShadowWolf** [comment]
Here is the debug log most recently: https://gist.github.com/DatrixTheHybridShadowWolf/6eee6b5751fd01c349041952d4a44cc0

This is the picture for the recipe for me right now:

![Wooden Tank](https://github.com/user-attachments/assets/76a21d2c-cb44-4e5f-84f5-4e33f38a53f2)

Since you are able to craft it, then it can only mean something is causing incompatibilities with the mod. I will be testing the mods so I can figure it out.

Edit: I figured it out. It turns out Forge-ified Fabric seems to be a culprit. I will put this issue in their github page as well.

https://github.com/Sinytra/ForgifiedFabricAPI/issues/154

**Comment by Kotori316** [comment]
It seems the fabric API conflicts with recipe condition. I add conditions for all platforms into just one file, and the fabric API might load the condition for fabric, but fails as it runs on Forge. Other recipes, such as `fluidtank:reservoir_wood` are loaded correctly as they don't use conditions.

```json
{
  "fabric:load_conditions": [
    {
      "condition": "fabric:tags_populated",
      "registry": "minecraft:item",
      "values": [
        "c:gems/emerald"
      ]
    }
  ],
  "type": "fluidtank:crafting_grade_up",
  "forge:condition": {
    "type": "forge:and",
    "values": [
      {
        "type": "forge:not",
        "value": {
          "type": "forge:tag_empty",
          "tag": "forge:gems/emerald"
        }
      }
    ]
  },
  "neoforge:conditions": [
    {
      "type": "neoforge:not",
      "value": {
        "type": "neoforge:tag_empty",
        "tag": "c:gems/emerald"
      }
    }
  ],
  "sub_item": {
    "fabric:type": "fluidtank:ignore_unknown_tag_ingredient",
    "type": "fluidtank:ignore_unknown_tag_ingredient",
    "values": [
      {
        "tag": "c:gems/emerald"
      },
      {
        "tag": "forge:gems/emerald"
      }
    ]
  },
  "tier": "EMERALD"
}
```

**Comment by DatrixTheHybridShadowWolf** [comment]
Thanks for the quick response and explaining it to me. I appreciate that.

**Comment by Kotori316** [comment]
Try v21.1.3

**Comment by DatrixTheHybridShadowWolf** [comment]
It now works. Thank you!
