### ISSUE TITLE
Causes crash on server

### ISSUE THREAD

**Issue by viktordimov** [Kotori316/FluidTank2#96]
[crash-report](https://pastebin.com/iLckGARq)

**Comment by Kotori316** [comment]
Show me the `latest.log`. The crash report doesn't contain enough info.

**Comment by viktordimov** [comment]
no problem
[crash-2024-03-03_00.40.01-server.txt](https://github.com/Kotori316/FluidTank2/files/14471211/crash-2024-03-03_00.40.01-server.txt)
[latest.log](https://github.com/Kotori316/FluidTank2/files/14471212/latest.log)

**Comment by Kotori316** [comment]
Thank you for the files. Try 20.12.1
